### PR TITLE
updated code to improve legend

### PR DESCRIPTION
**Pull request by kayneryan**
changed test.py, scatters.py and makefile. also uploaded new .png's and gif that include the new legend

### CODE REVIEW

**Comment by kayneryan** [comment]
I neglected to mention, this should close out Issue #59

**Review by PhilipMathieu — APPROVED** [review]
This is a clever solution to the problem. Just to make sure I am understanding, you are basically creating dummy plots with no data and generating the legends based off of those, allowing more control without having to tweak the plotting of the actual data?

**Review by sophiacofone — COMMENTED** [review]
This looks good to me!

**Review by sophiacofone — APPROVED** [review]

**Comment by sophiacofone** [comment]
@PhilipMathieu 
> This is a clever solution to the problem. Just to make sure I am understanding, you are basically creating dummy plots with no data and generating the legends based off of those, allowing more control without having to tweak the plotting of the actual data?

Yes, (@kayneryan correct me if I am misunderstanding) I believe that is what is going on here, you can "plot" some labeled data with no entries to get the legend looking how you want. Its a similar method as shown in cell 9 in the [https://jakevdp.github.io/PythonDataScienceHandbook/04.06-customizing-legends.html](book here).

**Comment by kayneryan** [comment]
Yes, that’s correct. Modeled on an example we covered in class, which I think is an elegant workaround that makes it much more viewer-friendly. Thanks!

Sent from my iPhone

On Mar 18, 2022, at 10:31 AM, Sophia Cofone ***@***.***> wrote:

﻿

@PhilipMathieu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPhilipMathieu&data=04%7C01%7Cryan.kay%40northeastern.edu%7C21d1bf0811b34da0827808da08ebf5b6%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637832106777268456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ewTlHYRgExeuXpJvl7lbaxmrMC95XVk%2BCq%2BcbrdMoKk%3D&reserved=0>

This is a clever solution to the problem. Just to make sure I am understanding, you are basically creating dummy plots with no data and generating the legends based off of those, allowing more control without having to tweak the plotting of the actual data?

Yes, ***@***.***<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkayneryan&data=04%7C01%7Cryan.kay%40northeastern.edu%7C21d1bf0811b34da0827808da08ebf5b6%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637832106777268456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=shpH6M1NneF15XY8rw5o2lrtVS3GTZCBupY7CULhNbM%3D&reserved=0> correct me if I am misunderstanding) I believe that is what is going on here, you can "plot" some labeled data with no entries to get the legend looking how you want. Its a similar method as shown in cell 9 in the [https://jakevdp.github.io/PythonDataScienceHandbook/04.06-customizing-legends.html](book here).

**Pull request merged**
